import {demoPatients,demoAppointments,demoPayments,monthlyRevenue,defaultSettings} from './data.js';
import {api,hasApi,getApiUrl,setApiUrl} from './api.js';
import {isoDate,validateEmail,validatePhone} from './utils.js';
import {dashboardView,patientsView,agendaView,financeView,reportsView,settingsView,patientModal,patientFormModal,appointmentFormModal,appointmentModal,paymentFormModal,quickMenu} from './render.js';

const state={route:'dashboard',patients:[...demoPatients],appointments:[...demoAppointments],payments:[...demoPayments],monthlyRevenue,settings:{...defaultSettings},patientQuery:'',patientFilter:'TODOS',agendaMode:'month',selectedDate:'2026-09-16',loading:false,demo:true,apiUrl:getApiUrl()};
const view=document.querySelector('#app-view');
const modalRoot=document.querySelector('#modal-root');
const title=document.querySelector('#page-title');

function routeLabel(route){return({dashboard:'Olá, Juliana',patients:'Pacientes',agenda:'Agenda',finance:'Financeiro',reports:'Relatórios',settings:'Configurações'})[route]}
function updateConnectionStatus(){const badge=document.querySelector('#api-status');const exitButton=document.querySelector('#exit-demo');badge.innerHTML=state.demo?'<i></i> Modo de demonstração':'<i class="connected"></i> Dados da planilha';badge.title=state.demo?'Os dados exibidos são exemplos e não serão gravados.':'Somente dados retornados pelo Google Sheets estão visíveis.';if(exitButton){exitButton.hidden=!state.demo;exitButton.disabled=state.loading;exitButton.textContent=state.loading?'Carregando…':'Sair do modo demo'}}
function render(){title.textContent=routeLabel(state.route);view.setAttribute('aria-busy','true');view.innerHTML=({dashboard:dashboardView,patients:patientsView,agenda:agendaView,finance:financeView,reports:reportsView,settings:settingsView})[state.route](state);view.setAttribute('aria-busy','false');document.querySelectorAll('[data-route]').forEach(el=>{el.classList.toggle('active',el.dataset.route===state.route);if(el.matches('.nav-item'))el.toggleAttribute('aria-current',el.dataset.route===state.route)});window.scrollTo({top:0,behavior:'smooth'});}
function navigate(route){if(!routeLabel(route))return;state.route=route;history.replaceState(null,'',`#${route}`);render()}
function showModal(html){modalRoot.innerHTML=html;document.body.classList.add('modal-open');requestAnimationFrame(()=>modalRoot.querySelector('input,select,button')?.focus())}
function closeModal(){modalRoot.innerHTML='';document.body.classList.remove('modal-open')}
function toast(message,type='success'){const item=document.createElement('div');item.className=`toast ${type}`;item.innerHTML=`<span>${type==='success'?'✓':'!'}</span><p>${message}</p>`;document.querySelector('#toast-root').append(item);setTimeout(()=>item.remove(),4200)}
function requireApi(){if(hasApi())return true;toast('Conecte a API do Google Apps Script em Configurações para salvar alterações.','error');return false}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function setSubmitting(form,busy){const button=form.querySelector('[type="submit"]');if(!button)return;if(!button.dataset.original)button.dataset.original=button.textContent;button.disabled=busy;button.textContent=busy?'Salvando…':button.dataset.original}

function buildMonthlyRevenue(payments){const base=new Date(`${state.selectedDate}T12:00:00`);return Array.from({length:6},(_,index)=>{const date=new Date(base.getFullYear(),base.getMonth()-5+index,1);const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;const value=payments.filter(payment=>payment.status==='PAGO'&&String(payment.date||'').startsWith(key)).reduce((sum,payment)=>sum+Number(payment.value||0),0);return{month:new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(date).replace('.',''),value}})}
async function loadRealData(){if(!hasApi())return false;state.loading=true;updateConnectionStatus();try{const [patients,appointments,payments,config]=await Promise.all([api.patients(),api.appointments(),api.payments(),api.config()]);state.patients=Array.isArray(patients)?patients:[];state.appointments=Array.isArray(appointments)?appointments:[];state.payments=Array.isArray(payments)?payments:[];state.monthlyRevenue=buildMonthlyRevenue(state.payments);state.settings={...state.settings,...config};state.demo=false;updateConnectionStatus();render();toast('Modo de demonstração encerrado. Exibindo somente os dados da planilha.');return true}catch{state.demo=true;updateConnectionStatus();toast('Não foi possível carregar a planilha. Confira a URL da API em Configurações.','error');return false}finally{state.loading=false;updateConnectionStatus()}}
async function exitDemoMode(){if(!hasApi()){navigate('settings');toast('Configure a URL da API do Google Apps Script para sair do modo demo.','error');return}await loadRealData()}
async function submitPatient(form){const data=formData(form);if(!data.first_name.trim())return toast('Informe o primeiro nome.','error');if(!data.type||!data.modality)return toast('Selecione tipo e modalidade.','error');if(!validateEmail(data.email))return toast('Informe um e-mail válido.','error');if(!validatePhone(data.phone))return toast('Informe um telefone válido.','error');if(Number(data.session_value)<0)return toast('Informe um valor de sessão válido.','error');if(!requireApi())return;setSubmitting(form,true);try{const editing=Boolean(data.patient_id);await (editing?api.updatePatient(data):api.createPatient(data));await loadRealData();closeModal();toast(editing?'Paciente atualizado com sucesso.':'Paciente cadastrado com sucesso.')}catch{toast('Não foi possível salvar o paciente.','error')}finally{setSubmitting(form,false)}}
async function submitAppointment(form){const data=formData(form);if(!data.patient_id||!data.date||!data.start_time||!data.end_time)return toast('Preencha paciente, data e horários.','error');if(data.end_time<=data.start_time)return toast('O horário final deve ser posterior ao inicial.','error');if(!requireApi())return;setSubmitting(form,true);try{await api.createAppointment(data);await loadRealData();closeModal();toast('Atendimento criado com sucesso.')}catch{toast('Não foi possível criar o atendimento.','error')}finally{setSubmitting(form,false)}}
async function submitPayment(form){const data=formData(form);if(!data.appointment_id||Number(data.value)<=0)return toast('Selecione o atendimento e informe um valor válido.','error');if(!requireApi())return;setSubmitting(form,true);try{const appointment=state.appointments.find(a=>a.appointment_id===data.appointment_id);await api.createPayment({...data,patient_id:appointment.patient_id,status:'PAGO'});await loadRealData();closeModal();toast('Pagamento registrado com sucesso.')}catch{toast('Não foi possível registrar o pagamento.','error')}finally{setSubmitting(form,false)}}
async function submitSettings(form){const data=formData(form);if(!validateEmail(data.email))return toast('Informe um e-mail válido.','error');setApiUrl(data.api_url);state.apiUrl=getApiUrl();state.settings={...state.settings,...data,default_session_value:Number(data.default_session_value),default_session_duration:Number(data.default_session_duration)};updateConnectionStatus();if(!hasApi()){render();toast('Preferências deste dispositivo atualizadas.');return}setSubmitting(form,true);try{await api.saveConfig(state.settings);toast('Configurações salvas com sucesso.');await loadRealData()}catch{toast('A URL foi guardada, mas não foi possível salvar as configurações na API.','error')}finally{setSubmitting(form,false)}}
async function updateAppointmentStatus(id,status){if(!requireApi())return;try{await api.updateAppointment({appointment_id:id,status});await loadRealData();closeModal();toast(`Atendimento marcado como ${status.toLowerCase()}.`)}catch{toast('Não foi possível atualizar o atendimento.','error')}}

document.addEventListener('click',event=>{
  if(event.target.classList.contains('modal-backdrop'))closeModal();
  const route=event.target.closest('[data-route]');if(route){navigate(route.dataset.route);return}
  const filter=event.target.closest('[data-filter]');if(filter){state.patientFilter=filter.dataset.filter;render();return}
  const mode=event.target.closest('[data-agenda-mode]');if(mode){state.agendaMode=mode.dataset.agendaMode;render();return}
  const dateButton=event.target.closest('[data-date]');if(dateButton){state.selectedDate=dateButton.dataset.date;if(state.agendaMode==='month')state.agendaMode='day';render();return}
  const action=event.target.closest('[data-action]');if(!action||action.classList.contains('modal-backdrop'))return;const id=action.dataset.id;
  switch(action.dataset.action){
    case'close-modal':closeModal();break;case'exit-demo':exitDemoMode();break;case'quick-menu':showModal(quickMenu());break;case'new-patient':showModal(patientFormModal());break;
    case'patient-detail':showModal(patientModal(state.patients.find(p=>p.patient_id===id),state));break;case'edit-patient':showModal(patientFormModal(state.patients.find(p=>p.patient_id===id)));break;
    case'new-appointment':showModal(appointmentFormModal(state,action.dataset.patientId||''));break;case'appointment-detail':showModal(appointmentModal(state.appointments.find(a=>a.appointment_id===id),state));break;case'new-payment':showModal(paymentFormModal(state,action.dataset.appointmentId||''));break;
    case'update-appointment-status':updateAppointmentStatus(id,action.dataset.status);break;case'today':state.selectedDate=isoDate(new Date());render();break;
    case'previous-month':{const d=new Date(`${state.selectedDate}T12:00:00`);d.setMonth(d.getMonth()-1);state.selectedDate=isoDate(d);render();break}case'next-month':{const d=new Date(`${state.selectedDate}T12:00:00`);d.setMonth(d.getMonth()+1);state.selectedDate=isoDate(d);render();break}
    case'previous-day':{const d=new Date(`${state.selectedDate}T12:00:00`);d.setDate(d.getDate()-1);state.selectedDate=isoDate(d);render();break}case'next-day':{const d=new Date(`${state.selectedDate}T12:00:00`);d.setDate(d.getDate()+1);state.selectedDate=isoDate(d);render();break}
  }
});
document.addEventListener('input',event=>{if(event.target.id==='patient-search'){state.patientQuery=event.target.value;const cursor=event.target.selectionStart;render();const input=document.querySelector('#patient-search');input?.focus();input?.setSelectionRange(cursor,cursor)}});
document.addEventListener('change',event=>{if(event.target.id==='appointment-patient'){const p=state.patients.find(item=>item.patient_id===event.target.value);if(!p)return;document.querySelector('#appointment-modality').value=p.modality;document.querySelector('#appointment-value').value=p.session_value;if(p.preferred_time){document.querySelector('#appointment-start').value=p.preferred_time;const[h,m]=p.preferred_time.split(':').map(Number);const end=new Date(2000,0,1,h,m+Number(state.settings.default_session_duration));document.querySelector('#appointment-end').value=`${String(end.getHours()).padStart(2,'0')}:${String(end.getMinutes()).padStart(2,'0')}`}}if(event.target.id==='payment-appointment'){const a=state.appointments.find(item=>item.appointment_id===event.target.value);if(a)document.querySelector('#payment-value').value=a.session_value}});
document.addEventListener('submit',event=>{event.preventDefault();if(event.target.id==='patient-form')submitPatient(event.target);if(event.target.id==='appointment-form')submitAppointment(event.target);if(event.target.id==='payment-form')submitPayment(event.target);if(event.target.id==='settings-form')submitSettings(event.target)});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});window.addEventListener('offline',()=>toast('Você está sem internet. Consultas em cache continuam disponíveis, mas não é possível salvar.','error'));window.addEventListener('online',()=>toast('Conexão restabelecida.'));

function registerWebMCP(){
  const context=document.modelContext;if(!context?.registerTool)return;
  const tools=[
    {name:'navigate_admin_page',title:'Abrir módulo',description:'Navega para um módulo administrativo visível do Psych Admin.',inputSchema:{type:'object',properties:{page:{type:'string',enum:['dashboard','patients','agenda','finance','reports','settings']}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute({page}){if(!routeLabel(page))throw new Error('Módulo inválido.');navigate(page);return{page}}},
    {name:'search_patients',title:'Buscar pacientes',description:'Busca pacientes pelo nome nos dados administrativos atualmente carregados.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute({query}){if(typeof query!=='string'||!query.trim())throw new Error('Informe um termo de busca.');return{matches:state.patients.filter(p=>p.full_name.toLowerCase().includes(query.trim().toLowerCase())).map(p=>({id:p.patient_id,name:p.full_name,status:p.status}))}}},
    {name:'start_appointment_creation',title:'Preparar novo atendimento',description:'Abre o formulário visível para criar um atendimento, sem salvar dados.',inputSchema:{type:'object',properties:{patientId:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute({patientId=''}){if(typeof patientId!=='string')throw new Error('patientId inválido.');if(patientId&&!state.patients.some(p=>p.patient_id===patientId))throw new Error('Paciente não encontrado.');showModal(appointmentFormModal(state,patientId));return{status:'form_opened',patientId:patientId||null}}}
  ];
  tools.forEach(tool=>Promise.resolve(context.registerTool(tool)).catch(()=>{}));
}
const initialRoute=location.hash.slice(1);if(routeLabel(initialRoute))state.route=initialRoute;const today=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());document.querySelector('#today-label').textContent=today[0].toUpperCase()+today.slice(1);updateConnectionStatus();render();registerWebMCP();if(hasApi())loadRealData();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
